apiVersion: apps/v1
kind: Deployment
metadata:
  name: appplication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: application
  template:
    metadata:
      labels:
        component: application
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: application
          imagePullPolicy: Always
          image: gitlab.cleevio.cz:4567/backend/vexl/vexl-chat-ms/staging:latest
          readinessProbe:
            httpGet:
              port: 8282
              path: /actuator/health
            initialDelaySeconds: 120
            timeoutSeconds: 20
            periodSeconds: 5
            failureThreshold: 10