name: "[Build] prod chat-ms image"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-prod-chat-ms:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Build offer2-ms java
        run: mvn package
             
      - name: Build and push prod chat-ms image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            http_proxy=$http_proxy
            https_proxy=$https_proxy
            no_proxy=$no_proxy
            CI_PROJECT_NAME=${{ github.repository }}
            CI_COMMIT_SHORT_SHA=${{ github.sha }}
            KUBE_DOMAIN=vexl.it
            PROFILE=prod
          tags: |
            ghcr.io/${{ github.repository_owner }}/chat-ms:latest
            ghcr.io/${{ github.repository_owner }}/chat-ms:${{ github.sha }}
